In [3]:
from scipy import stats
from IPython.display import HTML, display
import tabulate
import numpy as np

In [5]:
single_hop_data = """0.002874419	0.002874419	0.002874419	0.002874419	0.002874419
0.001050893	0.001031119	0.001091028	0.001009214	0.001016044
0.001366777	0.001296822	0.001248299	0.001243943	0.001253287
0.001009951	0.001052609	0.001007384	0.001051274	0.000980196
0.001090092	0.001165349	0.001040973	0.001201645	0.001204841
0.001262742	0.001224166	0.00113877	0.001184989	0.001102849
0.001320069	0.001331205	0.001247724	0.001297277	0.001212747
0.001519256	0.001519256	0.001519256	0.001519256	0.001519256
0.001092941	0.001062426	0.000987685	0.001066004	0.001029556
0.001008225	0.001109346	0.000971384	0.001045707	0.000971252
0.001571335	0.001571335	0.001571335	0.001571335	0.001571335
0.001274759	0.001109911	0.00104165	0.001069262	0.001045567
0.00150803	0.00150803	0.00150803	0.00150803	0.00150803
0.001205388	0.001207362	0.001207757	0.001209064	0.001170972
0.00108647	0.001094909	0.001006207	0.001121875	0.001005864
0.001088146	0.001165306	0.00107389	0.001112119	0.001035307
0.001313259	0.001274125	0.001269513	0.00127291	0.001269731
0.001307782	0.001264799	0.001252199	0.0012682	0.001240391
0.002051547	0.002010364	0.002010364	0.002010364	0.002010364
0.001533431	0.001413612	0.001413612	0.001413612	0.001413612
0.001205331	0.001205715	0.001169666	0.001153523	0.001169425
0.001196737	0.001176603	0.001171433	0.001171433	0.001171433
0.001705841	0.001705841	0.001705841	0.001705841	0.001705841
0.001458456	0.001458456	0.001458456	0.001458456	0.001458456
0.002191165	0.002191165	0.002191165	0.002191165	0.002191165
0.001596963	0.001596963	0.001596963	0.001596963	0.001596963
0.002336835	0.002336835	0.002336835	0.002336835	0.002336835
0.001933124	0.001933124	0.001933124	0.001933124	0.001933124
0.001865463	0.001826651	0.001826651	0.001826651	0.001826651
0.001524553	0.001401046	0.001401046	0.001401046	0.001401046
0.001772825	0.001756923	0.001758243	0.001755095	0.001756292
0.00266609	0.00266609	0.00266609	0.00266609	0.00266609
0.002956322	0.002956322	0.002956322	0.002956322	0.002956322
0.002388171	0.002388171	0.002388171	0.002388171	0.002388171
0.002703457	0.002703457	0.002703457	0.002703457	0.002703457
0.002685509	0.002685509	0.002685509	0.002685509	0.002685509
0.00257455	0.00248505	0.00248505	0.002514884	0.00248505
0.003026943	0.003026943	0.003026943	0.003026943	0.003026943
0.001778792	0.001751493	0.001751493	0.001751493	0.001751493
0.044051844	0.044051844	0.044051844	0.044051844	0.044051844"""

multi_hop_data = """0.002103287	0.001671054	0.00182141	0.001674311	0.001791669
0.001890697	0.001648535	0.001704093	0.001718202	0.001733998
0.002195557	0.001654061	0.001849282	0.00164468	0.001682028
0.001670601	0.001584103	0.001659764	0.001500296	0.001573724
0.001732869	0.001640488	0.001741474	0.001710044	0.0016763
0.001684406	0.001631598	0.001463193	0.001493115	0.001493492
0.00179346	0.001815054	0.001669948	0.001632889	0.001565694
0.001881884	0.001624282	0.001604347	0.001544135	0.001553241
0.001701081	0.001554809	0.001575012	0.001476149	0.001435714
0.001589264	0.001613239	0.001565761	0.001552377	0.001534379
0.001723348	0.001646742	0.001716787	0.001490254	0.001540532
0.001600103	0.001603054	0.001583481	0.001528581	0.001541625
0.001591159	0.001621369	0.001556289	0.001527162	0.001540887
0.001858377	0.001603927	0.001588276	0.001552302	0.001563073
0.001355083	0.001583958	0.001573809	0.001500921	0.00147376
0.001655619	0.001647763	0.001490087	0.001541479	0.001502962
0.001743687	0.001792812	0.001764782	0.001643218	0.00161905
0.001567959	0.001657366	0.001572819	0.001545866	0.00152119
0.001795231	0.002042336	0.002008067	0.001944998	0.001890206
0.001891852	0.00188402	0.001702137	0.00169974	0.001740181
0.00145008	0.001548157	0.001593713	0.001483148	0.0014601
0.001488829	0.001466415	0.00147956	0.001441655	0.001463422
0.001680699	0.001572611	0.001618643	0.001502597	0.001511046
0.001581289	0.001629852	0.001506924	0.001453127	0.001464836
0.001516268	0.001569473	0.001573565	0.001520979	0.001552444
0.001554467	0.001579704	0.001510863	0.001422944	0.001469312
0.001440238	0.001474527	0.001553889	0.001429653	0.001449194
0.001513255	0.001454971	0.00150048	0.001430147	0.001398936
0.001844222	0.001967078	0.00197407	0.00188732	0.001970339
0.001858068	0.001792942	0.001664974	0.001625841	0.001632414
0.002233339	0.001935892	0.002123764	0.002029869	0.00197054
0.002552289	0.002451218	0.001987116	0.002019921	0.002198601
0.002559184	0.002434084	0.002052022	0.002157643	0.002137904
0.002332306	0.002271896	0.002164595	0.002072222	0.002074722
0.002182174	0.00224656	0.002275844	0.002235253	0.002230782
0.00229196	0.001842267	0.001927152	0.002061061	0.001882821
0.002431355	0.002190584	0.002051867	0.002330802	0.002168105
0.002707655	0.001799719	0.002011933	0.002181611	0.001986098
0.002006303	0.001899524	0.001861176	0.001887528	0.001821271
0.002237519	0.002304416	0.002299946	0.002156089	0.002184617
0.001858434	0.001788728	0.00183257	0.001823981	0.001785422
0.001670301	0.001707399	0.001702691	0.001716724	0.00163005
0.001889033	0.00200069	0.001930403	0.001897981	0.001894573
0.002759601	0.002902087	0.002725804	0.002570868	0.002693845
0.002325601	0.002097746	0.002006523	0.001982459	0.002204462
0.001880268	0.001936867	0.00193192	0.001944019	0.001835261
0.001758977	0.001852212	0.001833989	0.001731625	0.001790687
0.001709668	0.001769628	0.001641955	0.001811838	0.001699173
0.003255685	0.003340451	0.003334756	0.003093	0.003061509
0.003055557	0.003213674	0.003135202	0.002938513	0.003041897"""

In [6]:
table = [['', 'MT2', 'MT31', 'MT13', 'MT6']]
for i in range(4):
    row = ['Type '+str(i+1)+'S']
    for mt in range(1, 5):
        ds1 = [float(tmp.split('\t')[0]) for tmp in single_hop_data.split('\n')][i*10:i*10+10]
        ds2 = [float(tmp.split('\t')[mt]) for tmp in single_hop_data.split('\n')][i*10:i*10+10]        
        val = stats.ttest_rel(ds1, ds2)
        row.append(round(val.pvalue/2,4)<0.05)
    table.append(row)
    
display(HTML(tabulate.tabulate(table, tablefmt='html')))

In [7]:
# table.append(['Multi', 'MT2', 'MT31', 'MT13', 'MT6'])
for i in range(5):
    row = ['Type '+str(i+1)+'M']
    for mt in range(1, 5):
        ds1 = [float(tmp.split('\t')[0]) for tmp in multi_hop_data.split('\n')][i*10:i*10+10]
        ds2 = [float(tmp.split('\t')[mt]) for tmp in multi_hop_data.split('\n')][i*10:i*10+10]
        val = stats.ttest_rel(ds1, ds2)
        row.append(round(val.pvalue/2,4)<0.05)
    table.append(row)
    
display(HTML(tabulate.tabulate(table, tablefmt='html')))

In [8]:
table = [[' ', 'MT2', 'MT31', 'MT13', 'MT6']]
for i in range(5):
    row = ['type '+str(i+1)]
    for mt in range(1, 5):
        ds1 = [float(tmp.split('\t')[0]) for tmp in multi_hop_data.split('\n')][i*10:i*10+10]
        ds2 = [float(tmp.split('\t')[mt]) for tmp in multi_hop_data.split('\n')][i*10:i*10+10]
        val = stats.ttest_rel(ds1, ds2)
        row.append(val.pvalue/2)
    table.append(row)
    
display(HTML(tabulate.tabulate(table, tablefmt='html')))

In [9]:
table = []
row = ['all']
for mt in range(1, 5):
    ds1 = [float(tmp.split('\t')[0]) for tmp in multi_hop_data.split('\n')]
    ds2 = [float(tmp.split('\t')[mt]) for tmp in multi_hop_data.split('\n')]
    val = stats.ttest_rel(ds1, ds2)
    row.append(round(val.pvalue/2,10))
table.append(row)
    
display(HTML(tabulate.tabulate(table, tablefmt='html')))

In [10]:
table = []
row = ['all']
for mt in range(1, 5):
    ds1 = [float(tmp.split('\t')[0]) for tmp in single_hop_data.split('\n')]
    ds2 = [float(tmp.split('\t')[mt]) for tmp in single_hop_data.split('\n')]
    val = stats.ttest_rel(ds1, ds2)
    row.append(round(val.pvalue/2,10))
table.append(row)
    
display(HTML(tabulate.tabulate(table, tablefmt='html')))

# Friedman test

In [11]:
single_hop_data = [[float(tmp1) for tmp1 in tmp.split('\t')] for tmp in single_hop_data.split('\n')]

In [12]:
single, mt2, mt31, mt13, mt6 = zip(*single_hop_data)

In [13]:
stats.friedmanchisquare(*[single, mt31, mt6])

FriedmanchisquareResult(statistic=29.388235294117667, pvalue=4.1536106989061125e-07)

In [14]:
import scikit_posthocs as sp
print(sp.posthoc_nemenyi_friedman(np.array([single, mt2, mt31, mt13, mt6]).T))
print()
print(sp.posthoc_miller_friedman(np.array([single, mt2, mt31, mt13, mt6]).T))

          0         1         2         3         4
0  1.000000  0.743201  0.011328  0.226127  0.001458
1  0.743201  1.000000  0.241843  0.883657  0.067537
2  0.011328  0.241843  1.000000  0.763265  0.900000
3  0.226127  0.883657  0.763265  1.000000  0.437421
4  0.001458  0.067537  0.900000  0.437421  1.000000

          0         1         2         3         4
0  1.000000  0.850901  0.034909  0.360551  0.006365
1  0.850901  1.000000  0.378972  0.932315  0.144310
2  0.034909  0.378972  1.000000  0.864760  0.988487
3  0.360551  0.932315  0.864760  1.000000  0.578104
4  0.006365  0.144310  0.988487  0.578104  1.000000


In [15]:
multi_hop_data = [[float(tmp1) for tmp1 in tmp.split('\t')] for tmp in multi_hop_data.split('\n')]

In [16]:
singlem, mt2m, mt31m, mt13m, mt6m = zip(*multi_hop_data)

In [17]:
stats.friedmanchisquare(*[singlem, mt2m, mt31m, mt13m, mt6m])

FriedmanchisquareResult(statistic=56.86400000000003, pvalue=1.3211711006547653e-11)

In [18]:
import scikit_posthocs as sp
print(sp.posthoc_nemenyi_friedman(np.array([singlem, mt2m, mt31m, mt13m, mt6m]).T))
print()
print(sp.posthoc_miller_friedman(np.array([singlem, mt2m, mt31m, mt13m, mt6m]).T))

          0         1         2         3      4
0  1.000000  0.900000  0.508007  0.001000  0.001
1  0.900000  1.000000  0.687481  0.001000  0.001
2  0.508007  0.687481  1.000000  0.002272  0.001
3  0.001000  0.001000  0.002272  1.000000  0.900
4  0.001000  0.001000  0.001000  0.900000  1.000

          0         1         2         3         4
0  1.000000  0.998791  0.644636  0.000015  0.000004
1  0.998791  1.000000  0.808792  0.000068  0.000021
2  0.644636  0.808792  1.000000  0.009250  0.003982
3  0.000015  0.000068  0.009250  1.000000  0.999499
4  0.000004  0.000021  0.003982  0.999499  1.000000


In [45]:
npar = np.array([singlem, mt2m, mt31m, mt13m, mt6m])
print(npar.shape)
ranks = np.argsort(npar, axis=0)+1

(5, 50)


In [46]:
print(np.mean(ranks, axis=1))

[3.44 4.16 3.14 2.52 1.74]


In [48]:
npar = np.array([single, mt2, mt31, mt13, mt6])

print(npar.shape)
ranks = np.argsort(npar, axis=0)+1
print(np.mean(ranks, axis=1))

(5, 40)
[2.5   2.8   3.025 3.55  3.125]


In [68]:
arg_vals = []
for i in np.array([single, mt2, mt31, mt13, mt6]).T:
    ord_ = [(tmp2, tmp1) for tmp1, tmp2 in enumerate(i)]
    arg_val = [0] * 5
    ord_ = sorted(ord_, key=lambda x: x[0])
    arg_val[ord_[0][1]] = 1
    print(ord_)
    
    current = 1
    for idx, (val, arg) in enumerate(ord_):
        if idx == 0:
            continue
        if val == ord_[idx-1][0]:
            arg_val[arg] = current
            continue
        else:
            current += 1
            arg_val[arg] = current
    if current == 1:
        continue
    arg_vals.append(arg_val)
    print(arg_val)

[(0.002874419, 0), (0.002874419, 1), (0.002874419, 2), (0.002874419, 3), (0.002874419, 4)]
[(0.001009214, 3), (0.001016044, 4), (0.001031119, 1), (0.001050893, 0), (0.001091028, 2)]
[4, 3, 5, 1, 2]
[(0.001243943, 3), (0.001248299, 2), (0.001253287, 4), (0.001296822, 1), (0.001366777, 0)]
[5, 4, 2, 1, 3]
[(0.000980196, 4), (0.001007384, 2), (0.001009951, 0), (0.001051274, 3), (0.001052609, 1)]
[3, 5, 2, 4, 1]
[(0.001040973, 2), (0.001090092, 0), (0.001165349, 1), (0.001201645, 3), (0.001204841, 4)]
[2, 3, 1, 4, 5]
[(0.001102849, 4), (0.00113877, 2), (0.001184989, 3), (0.001224166, 1), (0.001262742, 0)]
[5, 4, 2, 3, 1]
[(0.001212747, 4), (0.001247724, 2), (0.001297277, 3), (0.001320069, 0), (0.001331205, 1)]
[4, 5, 2, 3, 1]
[(0.001519256, 0), (0.001519256, 1), (0.001519256, 2), (0.001519256, 3), (0.001519256, 4)]
[(0.000987685, 2), (0.001029556, 4), (0.001062426, 1), (0.001066004, 3), (0.001092941, 0)]
[5, 3, 1, 4, 2]
[(0.000971252, 4), (0.000971384, 2), (0.001008225, 0), (0.001045707, 3

In [69]:
np.mean(arg_vals, axis=0)

array([3.43478261, 3.08695652, 1.86956522, 2.52173913, 1.52173913])

# sp.posthoc_conover_friedman(np.array([single, mt2, mt31, mt13, mt6]).T)

In [42]:
sp.posthoc_conover_friedman(np.array([singlem, mt2m, mt31m, mt13m, mt6m]).T)

0             1         2             3             4
0  1.000000e+00  7.531385e-01  0.116933  4.371256e-07  1.296924e-07
1  7.531385e-01  1.000000e+00  0.209247  1.886950e-06  5.886333e-07
2  1.169328e-01  2.092469e-01  1.000000  3.321989e-04  1.294336e-04
3  4.371256e-07  1.886950e-06  0.000332  1.000000e+00  8.013391e-01
4  1.296924e-07  5.886333e-07  0.000129  8.013391e-01  1.000000e+00

In [43]:
stats.friedmanchisquare(*[singlem, mt2m, mt31m, mt13m, mt6m])

FriedmanchisquareResult(statistic=56.86400000000003, pvalue=1.3211711006547653e-11)

In [44]:
stats.friedmanchisquare(*[single, mt2, mt31, mt13, mt6])

FriedmanchisquareResult(statistic=37.2139303482588, pvalue=1.627451584001758e-07)