In [2]:
from scipy import stats
from IPython.display import HTML, display
import tabulate
import numpy as np

In [3]:
single_hop_data = """0.001085559363	0.001084612087	0.001163792601	0.0009279220664	0.0008937856348	0.001083714531	0.0008979334616
0.002874419263	0.002874419263	0.002874419263	0.002874419263	0.002874419263	0.002874419263	0.002874419263
0.001648262292	0.001169209084	0.001092270038	0.00100692121	0.0008884342177	0.001040695647	0.0009711153325
0.001578959096	0.001332900756	0.001530027485	0.001231742845	0.00122219001	0.001184757152	0.0011913724
0.001013304285	0.00101798628	0.001017454484	0.0009678236935	0.0009342467	0.0009012319879	0.0008987624174
0.001402762473	0.001163496322	0.001164583221	0.0009673823211	0.0009313350091	0.0009720297855	0.001000766947
0.00122087752	0.001229495857	0.00122932141	0.001106964032	0.001108223944	0.001147931839	0.001184100709
0.001461581289	0.001331205109	0.001429308222	0.001215004237	0.001182087324	0.001310194431	0.001201774674
0.001578932479	0.001519255823	0.001519255823	0.001519255823	0.001519255823	0.001519255823	0.001519255823
0.001026193955	0.001104290067	0.001132553698	0.0009895377593	0.00098662452	0.001026566013	0.001019240492
0.001575648295	0.00141545317	0.001413611602	0.001413611602	0.00141545317	0.001413611602	0.00141545317
0.001571334719	0.001571334719	0.001571334719	0.001571334719	0.001571334719	0.001571334719	0.001571334719
0.001207613426	0.001229929911	0.001143008087	0.001108851835	0.001089402856	0.00100065603	0.001025243029
0.001508029765	0.001508029765	0.001508029765	0.001508029765	0.001508029765	0.001508029765	0.001508029765
0.001220427709	0.001191634884	0.001236366388	0.001196410684	0.001181322324	0.001182809942	0.001181322324
0.001051090199	0.001018981312	0.001165428391	0.001002607043	0.001005404268	0.001007173013	0.001005708625
0.00114219357	0.001196490988	0.001196526641	0.001065186869	0.001009649617	0.001019095071	0.001075868232
0.001418170901	0.00127881169	0.001269730977	0.001275026201	0.001273907727	0.001269730977	0.001269513494
0.001322344316	0.001279557239	0.001278706772	0.001244998831	0.001210370541	0.001250897625	0.001253525676
0.002050423719	0.002010364036	0.002010364036	0.002010364036	0.002010364036	0.002010364036	0.002010364036
0.001566161052	0.001401046302	0.001403840319	0.001401046302	0.001401046302	0.001401046302	0.001401046302
0.001380778338	0.001207180056	0.001193217436	0.001151279553	0.001152623663	0.001187569569	0.001152623663
0.001220021298	0.001197534836	0.001187416365	0.001171433489	0.001171433489	0.001171433489	0.001171433489
0.001705841081	0.001705841081	0.001705841081	0.001705841081	0.001705841081	0.001705841081	0.001705841081
0.00145845554	0.00145845554	0.00145845554	0.00145845554	0.00145845554	0.00145845554	0.00145845554
0.002191164824	0.002191164824	0.002191164824	0.002191164824	0.002191164824	0.002191164824	0.002191164824
0.00159696316	0.00159696316	0.00159696316	0.00159696316	0.00159696316	0.00159696316	0.00159696316
0.002336834824	0.002336834824	0.002336834824	0.002336834824	0.002336834824	0.002336834824	0.002336834824
0.00193312417	0.00193312417	0.00193312417	0.00193312417	0.00193312417	0.00193312417	0.00193312417
0.00193111085	0.00182665091	0.00182665091	0.00182665091	0.00182665091	0.00182665091	0.00182665091
0.04405184387	0.04405184387	0.04405184387	0.04405184387	0.04405184387	0.04405184387	0.04405184387
0.001784192112	0.001753832954	0.001789702254	0.001753832954	0.001756292221	0.001757734835	0.001755783894
0.002666090117	0.002666090117	0.002666090117	0.002666090117	0.002666090117	0.002666090117	0.002666090117
0.002956322107	0.002956322107	0.002956322107	0.002956322107	0.002956322107	0.002956322107	0.002956322107
0.002388170972	0.002388170972	0.002388170972	0.002388170972	0.002388170972	0.002388170972	0.002388170972
0.002707908757	0.002703457127	0.002703457127	0.002703457127	0.002703457127	0.002703457127	0.002703457127
0.00268550869	0.00268550869	0.00268550869	0.00268550869	0.00268550869	0.00268550869	0.00268550869
0.002574550194	0.002485050301	0.002485050301	0.002485050301	0.002485050301	0.002485050301	0.002485050301
0.003026942623	0.003026942623	0.003026942623	0.003026942623	0.003026942623	0.003026942623	0.003026942623
0.001771906232	0.001751492882	0.001771906232	0.001751492882	0.001751492882	0.001751492882	0.001751492882"""

multi_hop_data = """0.001089645724	0.001248971093	0.001144995989	0.001045023171	0.001000946222	0.001053488082	0.001064570071
0.001385912382	0.001414351652	0.001420815253	0.001179406664	0.001238485502	0.001260558625	0.001184978991
0.001248122725	0.001305032283	0.001267642817	0.001063750528	0.001128861174	0.001074345578	0.001091505233
0.001341286673	0.001433613161	0.001291972747	0.001112678619	0.001192888698	0.001155871593	0.001195643817
0.0013607781	0.001372700621	0.001352103342	0.001204095162	0.001239951774	0.001226127248	0.001207785898
0.001302638427	0.001348811742	0.001421740585	0.001183545816	0.001181524571	0.001252645675	0.001228505724
0.001165687966	0.00137539314	0.001430609396	0.001092884611	0.001138189517	0.001211335959	0.00115461225
0.001325300869	0.001464076135	0.001421238497	0.001162445891	0.001207192821	0.001282755736	0.001239577479
0.001293195307	0.001388348077	0.001433282246	0.001114737932	0.001155196699	0.001202795125	0.001081987532
0.001280885868	0.001432997404	0.001450395966	0.001198890794	0.001128926411	0.001158646049	0.001090676321
0.001047682152	0.001165868197	0.00108292906	0.0009760409535	0.001036797728	0.001079929772	0.001065016759
0.001076553607	0.001067034094	0.001000379297	0.0009156920972	0.0009646407238	0.0008699308408	0.0009002086883
0.0008769475352	0.001046662494	0.001072051568	0.0008274501974	0.0008528701457	0.0008720841004	0.0008725893795
0.0009951588696	0.001088253692	0.00101994909	0.0008877663141	0.0009147419225	0.0008948088953	0.0009234224897
0.001124620239	0.001207227898	0.00112231947	0.0009919581757	0.0009987883255	0.0009556484118	0.00105739515
0.0009951042027	0.001090973312	0.001070128101	0.0009598309377	0.0009523231823	0.0008907348746	0.0009608010087
0.001030040166	0.001097512374	0.001029596374	0.001018232963	0.0009807262399	0.0009062607507	0.0009679907608
0.001103525688	0.001320910461	0.001327572563	0.001165846412	0.001186628532	0.001102210143	0.001095804287
0.0009885068438	0.001069734477	0.0009507424839	0.0009476353189	0.0008757082815	0.0009485197882	0.0008918295213
0.001355994998	0.001365163154	0.001316375222	0.001188697404	0.001179954046	0.001099148083	0.001199457687
0.001265483765	0.001188751506	0.001228999915	0.001126985875	0.001064773245	0.001030075131	0.001045170462
0.0008431626705	0.000977863838	0.000910435241	0.0008451039851	0.0008577860471	0.0008360451922	0.0008434692431
0.0008075086595	0.0008555059019	0.0008260092652	0.0007596899826	0.0007355864032	0.0007395603782	0.0007502667726
0.0008244698785	0.0009572785325	0.0008318728367	0.0007865021982	0.000821527066	0.0008077877276	0.0008016245434
0.0008077215243	0.0009585115079	0.000834640589	0.0008148674351	0.0008186313055	0.0008086525089	0.0007973351557
0.0009834724989	0.0009490579055	0.0009589947201	0.0009589947201	0.0009434684989	0.0009434684989	0.0009434684989
0.0008462810819	0.0009051628161	0.0008383854076	0.000809048873	0.0008158955437	0.000806098626	0.0008209586929
0.0008275928973	0.000926410746	0.0008198839617	0.0007872678814	0.0007646600746	0.0007680343117	0.0008133638525
0.0008543720074	0.000957734176	0.0008455293699	0.0008305724414	0.0008446445933	0.0008085565332	0.0008104596424
0.001231061512	0.001307656464	0.001193438843	0.001068625228	0.001137965205	0.001094831417	0.001058612298
0.00125580754	0.001293340189	0.001164556471	0.00113102682	0.001126448941	0.001101442081	0.001097041699
0.001498402275	0.001636551854	0.001553470899	0.001287950423	0.001350201535	0.001380533736	0.001337555701
0.001614345875	0.001657410211	0.001434467553	0.001403574153	0.001468229692	0.001393117735	0.001346466133
0.001635704644	0.001673138292	0.001592238002	0.00138218087	0.001305823467	0.001408519404	0.001368707981
0.001580498293	0.00158218016	0.001711765399	0.001398971831	0.001415869941	0.00143131313	0.00144037653
0.001413101108	0.001496049699	0.001387817867	0.001243710802	0.001309276991	0.001248227686	0.001319470779
0.001811921511	0.001860023269	0.001681007703	0.001618177708	0.001622992666	0.001554914953	0.001607859314
0.001619889457	0.001804007756	0.001728573235	0.00147344083	0.00147798999	0.001483458007	0.001468830725
0.00173008431	0.001829253199	0.001629797802	0.001582386319	0.001501727416	0.001530345032	0.001483998155
0.001306569906	0.00151784117	0.001388494732	0.001286507426	0.001275875211	0.001204270569	0.001219892193
0.001455417553	0.001672782339	0.00181831643	0.001291761582	0.001278120013	0.001232007147	0.001285288886
0.007200730829	0.007200722961	0.00720072167	0.006800697704	0.006800686053	0.006800684975	0.006800689395
0.00456063603	0.004520749806	0.004440532672	0.004040577632	0.004080828321	0.004040651191	0.004160824665
0.003920436102	0.003975418248	0.003924014284	0.003647514316	0.003604006725	0.003600408074	0.003563887812
0.001437299341	0.001644788237	0.001597370509	0.001462969291	0.001459540433	0.001324265046	0.001418937886
0.002724515676	0.002723835602	0.002902183291	0.0022014771	0.002281185247	0.00224057677	0.002323100787
0.002465442122	0.002430938328	0.002470455664	0.002391764585	0.002366885215	0.002249433759	0.002257831915
0.004360464553	0.004240533034	0.004040433349	0.003800575463	0.003680457634	0.0036404465	0.003680596448
0.004481522871	0.004416852093	0.004321413718	0.003752329622	0.004151941125	0.003805440034	0.003867128781
0.00150936095	0.001707037314	0.001842422005	0.001479831496	0.001493026774	0.001443893174	0.001475661107"""

# Friedman test

In [4]:
single_hop_data = [[float(tmp1) for tmp1 in tmp.split('\t')] for tmp in single_hop_data.split('\n')]

In [5]:
ga, pso, de, mt2, mt31, mt13, mt6 = zip(*single_hop_data)

In [6]:
stats.friedmanchisquare(*[ga, pso, de, mt6])

FriedmanchisquareResult(statistic=38.601769911504334, pvalue=2.107747993492999e-08)

In [7]:
multi_hop_data = [[float(tmp1) for tmp1 in tmp.split('\t')] for tmp in multi_hop_data.split('\n')]

In [8]:
gam, psom, dem, mt2m, mt31m, mt13m, mt6m = zip(*multi_hop_data)

In [9]:
stats.friedmanchisquare(*[gam, psom, dem, mt6m])

FriedmanchisquareResult(statistic=99.76800000000003, pvalue=1.7433282565865083e-21)

In [32]:
print(np.mean(ranks, axis=1))

[3.42 3.66 3.3  3.36 1.26]


In [27]:
arg_vals = []
for i in np.array([ga, pso, de, mt6]).T:
    ord_ = [(tmp2, tmp1) for tmp1, tmp2 in enumerate(i)]
    arg_val = [0] * 4
    ord_ = sorted(ord_, key=lambda x: x[0])
    arg_val[ord_[0][1]] = 1
    current = 1
    for idx, (val, arg) in enumerate(ord_):
        if idx == 0:
            continue
        if val == ord_[idx-1][0]:
            arg_val[arg] = current
            continue
        else:
            current += 1
            arg_val[arg] = current
    if current == 1:
        continue
    arg_vals.append(arg_val)
    
np.mean(arg_vals, axis=0)

array([2.92, 2.2 , 2.44, 1.08])

In [26]:
arg_vals = []
for i in np.array([gam, psom, dem, mt6m]).T:
    ord_ = [(tmp2, tmp1) for tmp1, tmp2 in enumerate(i)]
    arg_val = [0] * 4
    ord_ = sorted(ord_, key=lambda x: x[0])
    arg_val[ord_[0][1]] = 1
#     print(ord_)
    
    current = 1
    for idx, (val, arg) in enumerate(ord_):
        if idx == 0:
            continue
        if val == ord_[idx-1][0]:
            arg_val[arg] = current
            continue
        else:
            current += 1
            arg_val[arg] = current
    if current == 1:
        continue
    arg_vals.append(arg_val)
np.mean(arg_vals, axis=0)

array([2.6 , 3.54, 2.82, 1.04])

# sp.posthoc_conover_friedman(np.array([single, mt2, mt31, mt13, mt6]).T)

In [20]:
import scikit_posthocs as sp

In [22]:
sp.posthoc_conover_friedman(np.array([ga, pso, de, mt6]).T)

0         1         2             3
0  1.000000e+00  0.004558  0.039465  1.209993e-08
1  4.558339e-03  1.000000  0.419638  1.558362e-03
2  3.946512e-02  0.419638  1.000000  9.259376e-05
3  1.209993e-08  0.001558  0.000093  1.000000e+00

In [23]:
sp.posthoc_conover_friedman(np.array([gam, psom, dem, mt6m]).T)

0             1             2             3
0  1.000000e+00  3.886809e-04  3.967678e-01  1.288581e-08
1  3.886809e-04  1.000000e+00  6.121027e-03  2.159718e-17
2  3.967678e-01  6.121027e-03  1.000000e+00  1.634342e-10
3  1.288581e-08  2.159718e-17  1.634342e-10  1.000000e+00

In [24]:
3.886809e-04*100

0.03886809

In [25]:
1.558362e-03*100

0.1558362